spring.application.name=employeeManagementBackend
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=krinainamdar
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true

# Security CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173
