stages:
  - lint
  - build
  - security

# Cache speeds up builds
cache:
  paths:
    - backend/.m2/repository
    - employee-frontend/node_modules/

# -------------------------
# FRONTEND LINT
# -------------------------
frontend-lint:
  stage: lint
  image: node:20
  script:
    - cd employee-frontend
    - npm install
    - npm run lint || echo "No lint script found"
  rules:
    - if: $CI_COMMIT_BRANCH

# -------------------------
# BACKEND BUILD
# -------------------------
backend-build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
  rules:
    - if: $CI_COMMIT_BRANCH

# -------------------------
# FRONTEND BUILD
# -------------------------
frontend-build:
  stage: build
  image: node:20
  script:
    - cd employee-frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - employee-frontend/build/
  rules:
    - if: $CI_COMMIT_BRANCH

# -------------------------
# SECURITY SCAN
# -------------------------
dependency-security-scan:
  stage: security
  image: node:20
  script:
    - cd employee-frontend
    - npm install
    - npm audit --audit-level=high
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH